update deployer

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -81,40 +81,26 @@ jobs:
             docker rename everyday_shop_app everyday_shop_app_backup || true
 
             echo "🚀 Starting new container..."
+
+            docker stop everyday_shop_app || true
+            docker rm everyday_shop_app || true
+            docker volume rm everyday_shop_cache || true
+
             if docker run -d \
               --name everyday_shop_app \
               --env-file /var/www/everyday_shop/.env \
               -v everyday_shop_storage:/var/www/everyday_shop/storage \
-              -v everyday_shop_cache:/var/www/everyday_shop/bootstrap/cache \
               --network global_network \
               -p 8080:80 \
               ${{ env.IMAGE_NAME }}:latest; then
 
               echo "✅ Deployment successful!"
-              docker rm -f everyday_shop_app_backup || true
 
-              echo "🗝️ Checking APP_KEY..."
-              docker exec everyday_shop_app bash -c '
-                if ! grep -q "APP_KEY=base64:" /var/www/everyday_shop/.env; then
-                  echo "⚙️ Generating new APP_KEY..."
-                  php artisan key:generate --force
-                else
-                  echo "✅ APP_KEY already set."
-                fi
-              '
-
-              # echo "🔁 Running migrations..."
-              # docker exec everyday_shop_app php artisan migrate --force || true
-
-              # echo "🔗 Fixing storage symlink..."
-              # docker exec everyday_shop_app php artisan storage:link || true
-
-              # echo "🧹 Clearing Laravel caches..."
-              # docker exec everyday_shop_app php artisan optimize:clear || true
+              echo "🧹 Clearing Laravel cache..."
+              docker exec everyday_shop_app php artisan optimize:clear
 
             else
-              echo "❌ Deployment failed. Rolling back..."
-              docker rm -f everyday_shop_app || true
-              docker rename everyday_shop_app_backup everyday_shop_app || true
-              docker start everyday_shop_app
+              echo "❌ Deployment failed"
+              exit 1
             fi
+
